# Generated by Django 4.2.1 on 2023-05-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
